version: '3.1'

volumes:
  mongo_data: {}

services:
  web:
    image: yahyaqandel/express-lib:3
    ports:
    - "80:3000"
    - "9229:9229"
    depends_on:
    - mongo
    deploy:
      replicas: 3
    networks:
      - general

  mongo:
    image: mongo:4.0-xenial
    volumes:
    - mongo_data:/data/db
    ports:
    - "27017:27017"

networks:
  general:
    driver: overlay
