version: '3.1'

volumes:
  mongo_data: {}

services:
    web:
        image: node
        env_file:
          - dev.env
        volumes:
          - .:/app
          - /app/node_modules
        ports:
          - "80:3000"
          - "9229:9229"
        depends_on:
          - mongo
        deploy:
          replicas: 3

    mongo:
        image: mongo:4.0-xenial
        volumes:
          - mongo_data:/data/db
        ports:
          - "27017:27017"

