version: '3'

volumes:
  mongo_data: {}

services:
    web:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
          - .:/app
        ports:
          - "80:3000"
        depends_on:
          - mongo
    mongo:
        image: mongo:4.0-xenial
        volumes:
          - mongo_data:/data/db
        ports:
          - "27017:27017"

